# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\github\final_work\final_work_最终版\gray_enhance.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(602, 192)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(80, 40, 461, 81))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.line_5 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout.addWidget(self.line_5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10, 0, QtCore.Qt.AlignLeft)
        self.value_linear_a = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.value_linear_a.setMaximum(256)
        self.value_linear_a.setObjectName("value_linear_a")
        self.horizontalLayout_4.addWidget(self.value_linear_a)
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11, 0, QtCore.Qt.AlignHCenter)
        self.value_linear_b = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.value_linear_b.setMaximum(256)
        self.value_linear_b.setObjectName("value_linear_b")
        self.horizontalLayout_4.addWidget(self.value_linear_b)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12, 0, QtCore.Qt.AlignLeft)
        self.value_power_a = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.value_power_a.setMaximum(256)
        self.value_power_a.setObjectName("value_power_a")
        self.horizontalLayout_5.addWidget(self.value_power_a)
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13, 0, QtCore.Qt.AlignLeft)
        self.value_power_b = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.value_power_b.setSingleStep(0.5)
        self.value_power_b.setObjectName("value_power_b")
        self.horizontalLayout_5.addWidget(self.value_power_b)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.line_6 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout.addWidget(self.line_6)
        self.verticalLayout1 = QtWidgets.QVBoxLayout()
        self.verticalLayout1.setObjectName("verticalLayout1")
        self.submit_linear = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.submit_linear.setObjectName("submit_linear")
        self.verticalLayout1.addWidget(self.submit_linear)
        self.submit_power = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.submit_power.setObjectName("submit_power")
        self.verticalLayout1.addWidget(self.submit_power)
        self.horizontalLayout.addLayout(self.verticalLayout1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 602, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "灰度图像增强"))
        self.label_4.setText(_translate("MainWindow", "分段线性变换"))
        self.label_5.setText(_translate("MainWindow", "幂变换"))
        self.label_10.setText(_translate("MainWindow", "分界点a"))
        self.label_11.setText(_translate("MainWindow", "分界点b"))
        self.label_12.setText(_translate("MainWindow", "灰度拉升系数a"))
        self.label_13.setText(_translate("MainWindow", "gamma系数b"))
        self.submit_linear.setText(_translate("MainWindow", "确认"))
        self.submit_power.setText(_translate("MainWindow", "确认"))

