# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\github\final_work\final_work_最终版\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(984, 653)
        MainWindow.setIconSize(QtCore.QSize(128, 128))
        self.main_centralwidget = QtWidgets.QWidget(MainWindow)
        self.main_centralwidget.setObjectName("main_centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main_centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.MainWidget = QtWidgets.QWidget(self.main_centralwidget)
        self.MainWidget.setObjectName("MainWidget")
        self.MainLayout = QtWidgets.QHBoxLayout(self.MainWidget)
        self.MainLayout.setObjectName("MainLayout")
        self.img_MainWidget = QtWidgets.QWidget(self.MainWidget)
        self.img_MainWidget.setObjectName("img_MainWidget")
        self.img_MainLayout = QtWidgets.QHBoxLayout(self.img_MainWidget)
        self.img_MainLayout.setObjectName("img_MainLayout")
        self.widget_thumb = QtWidgets.QWidget(self.img_MainWidget)
        self.widget_thumb.setObjectName("widget_thumb")
        self.layout_thumb = QtWidgets.QVBoxLayout(self.widget_thumb)
        self.layout_thumb.setObjectName("layout_thumb")
        self.label_thumb = QtWidgets.QLabel(self.widget_thumb)
        self.label_thumb.setObjectName("label_thumb")
        self.layout_thumb.addWidget(self.label_thumb, 0, QtCore.Qt.AlignHCenter)
        self.layout_thumb_origin = QtWidgets.QVBoxLayout()
        self.layout_thumb_origin.setObjectName("layout_thumb_origin")
        self.label_origin = QtWidgets.QLabel(self.widget_thumb)
        self.label_origin.setObjectName("label_origin")
        self.layout_thumb_origin.addWidget(self.label_origin)
        self.thumb_origin = QtWidgets.QLabel(self.widget_thumb)
        self.thumb_origin.setScaledContents(False)
        self.thumb_origin.setAlignment(QtCore.Qt.AlignCenter)
        self.thumb_origin.setObjectName("thumb_origin")
        self.layout_thumb_origin.addWidget(self.thumb_origin)
        self.layout_thumb_origin.setStretch(0, 1)
        self.layout_thumb_origin.setStretch(1, 9)
        self.layout_thumb.addLayout(self.layout_thumb_origin)
        self.layout_thumb_prev = QtWidgets.QVBoxLayout()
        self.layout_thumb_prev.setObjectName("layout_thumb_prev")
        self.label_prev = QtWidgets.QLabel(self.widget_thumb)
        self.label_prev.setObjectName("label_prev")
        self.layout_thumb_prev.addWidget(self.label_prev)
        self.thumb_prev = QtWidgets.QLabel(self.widget_thumb)
        self.thumb_prev.setScaledContents(False)
        self.thumb_prev.setAlignment(QtCore.Qt.AlignCenter)
        self.thumb_prev.setObjectName("thumb_prev")
        self.layout_thumb_prev.addWidget(self.thumb_prev)
        self.layout_thumb_prev.setStretch(0, 1)
        self.layout_thumb_prev.setStretch(1, 9)
        self.layout_thumb.addLayout(self.layout_thumb_prev)
        self.layout_thumb.setStretch(0, 1)
        self.layout_thumb.setStretch(1, 10)
        self.layout_thumb.setStretch(2, 10)
        self.img_MainLayout.addWidget(self.widget_thumb)
        self.widget_big_prev = QtWidgets.QWidget(self.img_MainWidget)
        self.widget_big_prev.setObjectName("widget_big_prev")
        self.layout_big_prev = QtWidgets.QVBoxLayout(self.widget_big_prev)
        self.layout_big_prev.setObjectName("layout_big_prev")
        self.label_big_prev = QtWidgets.QLabel(self.widget_big_prev)
        self.label_big_prev.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.label_big_prev.setAlignment(QtCore.Qt.AlignCenter)
        self.label_big_prev.setObjectName("label_big_prev")
        self.layout_big_prev.addWidget(self.label_big_prev)
        self.scrollArea_prev = QtWidgets.QScrollArea(self.widget_big_prev)
        self.scrollArea_prev.setWidgetResizable(True)
        self.scrollArea_prev.setObjectName("scrollArea_prev")
        self.scroolWidget_big_prev = QtWidgets.QWidget()
        self.scroolWidget_big_prev.setGeometry(QtCore.QRect(0, 0, 719, 342))
        self.scroolWidget_big_prev.setObjectName("scroolWidget_big_prev")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scroolWidget_big_prev)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.big_prev = QtWidgets.QLabel(self.scroolWidget_big_prev)
        self.big_prev.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.big_prev.setAlignment(QtCore.Qt.AlignCenter)
        self.big_prev.setObjectName("big_prev")
        self.verticalLayout_5.addWidget(self.big_prev)
        self.scrollArea_prev.setWidget(self.scroolWidget_big_prev)
        self.layout_big_prev.addWidget(self.scrollArea_prev)
        self.layout_big_prev.setStretch(1, 20)
        self.img_MainLayout.addWidget(self.widget_big_prev)
        self.img_MainLayout.setStretch(0, 1)
        self.img_MainLayout.setStretch(1, 4)
        self.MainLayout.addWidget(self.img_MainWidget)
        self.MainLayout.setStretch(0, 5)
        self.verticalLayout_2.addWidget(self.MainWidget)
        self.JHBH_widget = QtWidgets.QWidget(self.main_centralwidget)
        self.JHBH_widget.setObjectName("JHBH_widget")
        self.layout_PY = QtWidgets.QHBoxLayout(self.JHBH_widget)
        self.layout_PY.setObjectName("layout_PY")
        self.layout_PY_2 = QtWidgets.QHBoxLayout()
        self.layout_PY_2.setContentsMargins(-1, -1, -1, 0)
        self.layout_PY_2.setObjectName("layout_PY_2")
        self.label_V = QtWidgets.QLabel(self.JHBH_widget)
        self.label_V.setObjectName("label_V")
        self.layout_PY_2.addWidget(self.label_V)
        self.slider_PY_V = QtWidgets.QSlider(self.JHBH_widget)
        self.slider_PY_V.setOrientation(QtCore.Qt.Horizontal)
        self.slider_PY_V.setObjectName("slider_PY_V")
        self.layout_PY_2.addWidget(self.slider_PY_V)
        self.label_S = QtWidgets.QLabel(self.JHBH_widget)
        self.label_S.setObjectName("label_S")
        self.layout_PY_2.addWidget(self.label_S)
        self.slider_PY_S = QtWidgets.QSlider(self.JHBH_widget)
        self.slider_PY_S.setOrientation(QtCore.Qt.Horizontal)
        self.slider_PY_S.setObjectName("slider_PY_S")
        self.layout_PY_2.addWidget(self.slider_PY_S)
        self.layout_PY.addLayout(self.layout_PY_2)
        self.line = QtWidgets.QFrame(self.JHBH_widget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layout_PY.addWidget(self.line)
        self.widget_JX = QtWidgets.QWidget(self.JHBH_widget)
        self.widget_JX.setObjectName("widget_JX")
        self.layout_JX = QtWidgets.QHBoxLayout(self.widget_JX)
        self.layout_JX.setObjectName("layout_JX")
        self.JX_s = QtWidgets.QPushButton(self.widget_JX)
        self.JX_s.setObjectName("JX_s")
        self.layout_JX.addWidget(self.JX_s)
        self.JX_v = QtWidgets.QPushButton(self.widget_JX)
        self.JX_v.setObjectName("JX_v")
        self.layout_JX.addWidget(self.JX_v)
        self.layout_PY.addWidget(self.widget_JX)
        self.line_2 = QtWidgets.QFrame(self.JHBH_widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.layout_PY.addWidget(self.line_2)
        self.layout_XZ = QtWidgets.QHBoxLayout()
        self.layout_XZ.setObjectName("layout_XZ")
        self.label = QtWidgets.QLabel(self.JHBH_widget)
        self.label.setObjectName("label")
        self.layout_XZ.addWidget(self.label)
        self.slider_XZ = QtWidgets.QSlider(self.JHBH_widget)
        self.slider_XZ.setOrientation(QtCore.Qt.Horizontal)
        self.slider_XZ.setObjectName("slider_XZ")
        self.layout_XZ.addWidget(self.slider_XZ)
        self.layout_PY.addLayout(self.layout_XZ)
        self.line_3 = QtWidgets.QFrame(self.JHBH_widget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.layout_PY.addWidget(self.line_3)
        self.label_SF = QtWidgets.QLabel(self.JHBH_widget)
        self.label_SF.setObjectName("label_SF")
        self.layout_PY.addWidget(self.label_SF)
        self.line_4 = QtWidgets.QFrame(self.JHBH_widget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.layout_PY.addWidget(self.line_4)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_PY.addItem(spacerItem1)
        self.layout_PY.setStretch(8, 3)
        self.verticalLayout_2.addWidget(self.JHBH_widget)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.setStretch(1, 8)
        MainWindow.setCentralWidget(self.main_centralwidget)
        self.main_menubar = QtWidgets.QMenuBar(MainWindow)
        self.main_menubar.setGeometry(QtCore.QRect(0, 0, 984, 40))
        self.main_menubar.setObjectName("main_menubar")
        self.menu_file = QtWidgets.QMenu(self.main_menubar)
        self.menu_file.setObjectName("menu_file")
        self.title_about = QtWidgets.QMenu(self.main_menubar)
        self.title_about.setObjectName("title_about")
        self.menu_edit = QtWidgets.QMenu(self.main_menubar)
        self.menu_edit.setObjectName("menu_edit")
        self.menu_noise_fliter = QtWidgets.QMenu(self.main_menubar)
        self.menu_noise_fliter.setObjectName("menu_noise_fliter")
        self.menu_gray_enhance = QtWidgets.QMenu(self.main_menubar)
        self.menu_gray_enhance.setObjectName("menu_gray_enhance")
        self.menu_4 = QtWidgets.QMenu(self.main_menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.main_menubar)
        self.menu_5.setObjectName("menu_5")
        self.menu = QtWidgets.QMenu(self.main_menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.main_menubar)
        self.main_statusbar = QtWidgets.QStatusBar(MainWindow)
        self.main_statusbar.setObjectName("main_statusbar")
        MainWindow.setStatusBar(self.main_statusbar)
        self.actioninfo = QtWidgets.QAction(MainWindow)
        self.actioninfo.setObjectName("actioninfo")
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.action_quit = QtWidgets.QAction(MainWindow)
        self.action_quit.setObjectName("action_quit")
        self.action_open = QtWidgets.QAction(MainWindow)
        self.action_open.setObjectName("action_open")
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setObjectName("action_save")
        self.action_mean_filter = QtWidgets.QAction(MainWindow)
        self.action_mean_filter.setObjectName("action_mean_filter")
        self.action_gauss_fliter = QtWidgets.QAction(MainWindow)
        self.action_gauss_fliter.setObjectName("action_gauss_fliter")
        self.action_median_filter = QtWidgets.QAction(MainWindow)
        self.action_median_filter.setObjectName("action_median_filter")
        self.action_linear = QtWidgets.QAction(MainWindow)
        self.action_linear.setObjectName("action_linear")
        self.action_power = QtWidgets.QAction(MainWindow)
        self.action_power.setObjectName("action_power")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_7 = QtWidgets.QAction(MainWindow)
        self.action_7.setObjectName("action_7")
        self.action_2gray = QtWidgets.QAction(MainWindow)
        self.action_2gray.setObjectName("action_2gray")
        self.action_2binary = QtWidgets.QAction(MainWindow)
        self.action_2binary.setObjectName("action_2binary")
        self.action_color_reverse = QtWidgets.QAction(MainWindow)
        self.action_color_reverse.setObjectName("action_color_reverse")
        self.action_gaussian_noise = QtWidgets.QAction(MainWindow)
        self.action_gaussian_noise.setObjectName("action_gaussian_noise")
        self.action_salt_noise = QtWidgets.QAction(MainWindow)
        self.action_salt_noise.setObjectName("action_salt_noise")
        self.action_own_2gray = QtWidgets.QAction(MainWindow)
        self.action_own_2gray.setObjectName("action_own_2gray")
        self.action_own_2binary = QtWidgets.QAction(MainWindow)
        self.action_own_2binary.setObjectName("action_own_2binary")
        self.action_noisy_menu = QtWidgets.QAction(MainWindow)
        self.action_noisy_menu.setObjectName("action_noisy_menu")
        self.action_gray_enhance_menu = QtWidgets.QAction(MainWindow)
        self.action_gray_enhance_menu.setObjectName("action_gray_enhance_menu")
        self.action_hdzft = QtWidgets.QAction(MainWindow)
        self.action_hdzft.setObjectName("action_hdzft")
        self.menu_file.addAction(self.action_open)
        self.menu_file.addAction(self.action_save)
        self.menu_file.addAction(self.action_quit)
        self.title_about.addAction(self.action_about)
        self.menu_edit.addAction(self.action_2gray)
        self.menu_edit.addAction(self.action_2binary)
        self.menu_noise_fliter.addAction(self.action_salt_noise)
        self.menu_noise_fliter.addAction(self.action_gaussian_noise)
        self.menu_noise_fliter.addSeparator()
        self.menu_noise_fliter.addAction(self.action_mean_filter)
        self.menu_noise_fliter.addAction(self.action_median_filter)
        self.menu_noise_fliter.addAction(self.action_gauss_fliter)
        self.menu_noise_fliter.addSeparator()
        self.menu_noise_fliter.addAction(self.action_noisy_menu)
        self.menu_gray_enhance.addAction(self.action_linear)
        self.menu_gray_enhance.addAction(self.action_power)
        self.menu_gray_enhance.addAction(self.action_hdzft)
        self.menu_gray_enhance.addSeparator()
        self.menu_gray_enhance.addAction(self.action_gray_enhance_menu)
        self.menu_4.addAction(self.action_6)
        self.menu_4.addAction(self.action_7)
        self.menu.addAction(self.action_own_2gray)
        self.menu.addAction(self.action_own_2binary)
        self.main_menubar.addAction(self.menu_file.menuAction())
        self.main_menubar.addAction(self.menu_edit.menuAction())
        self.main_menubar.addAction(self.menu_5.menuAction())
        self.main_menubar.addAction(self.menu_noise_fliter.menuAction())
        self.main_menubar.addAction(self.menu_gray_enhance.menuAction())
        self.main_menubar.addAction(self.menu_4.menuAction())
        self.main_menubar.addAction(self.menu.menuAction())
        self.main_menubar.addAction(self.title_about.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "图像处理-wjsaya.top"))
        self.label_thumb.setText(_translate("MainWindow", "想放大哪一个?点击就好"))
        self.label_origin.setText(_translate("MainWindow", "原图"))
        self.thumb_origin.setText(_translate("MainWindow", "thumb_origin"))
        self.label_prev.setText(_translate("MainWindow", "当前修改"))
        self.thumb_prev.setText(_translate("MainWindow", "thumb_prev"))
        self.label_big_prev.setText(_translate("MainWindow", "当前是什么?"))
        self.big_prev.setText(_translate("MainWindow", "big_prev"))
        self.label_V.setText(_translate("MainWindow", "垂直平移"))
        self.label_S.setText(_translate("MainWindow", "水平平移"))
        self.JX_s.setText(_translate("MainWindow", "垂直镜像"))
        self.JX_v.setText(_translate("MainWindow", "水平镜像"))
        self.label.setText(_translate("MainWindow", "旋转"))
        self.label_SF.setText(_translate("MainWindow", "缩放请使用ctrl+鼠标滚轮"))
        self.menu_file.setTitle(_translate("MainWindow", "文件"))
        self.title_about.setTitle(_translate("MainWindow", "关于"))
        self.menu_edit.setTitle(_translate("MainWindow", "编辑"))
        self.menu_noise_fliter.setTitle(_translate("MainWindow", "加噪去噪"))
        self.menu_gray_enhance.setTitle(_translate("MainWindow", "    灰度图像增强\n"
""))
        self.menu_4.setTitle(_translate("MainWindow", "边缘提取"))
        self.menu_5.setTitle(_translate("MainWindow", "几何变换"))
        self.menu.setTitle(_translate("MainWindow", "自己实现的函数"))
        self.actioninfo.setText(_translate("MainWindow", "info"))
        self.action_about.setText(_translate("MainWindow", "关于我们"))
        self.action_quit.setText(_translate("MainWindow", "退出程序"))
        self.action_quit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.action_open.setText(_translate("MainWindow", "打开图片"))
        self.action_open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_save.setText(_translate("MainWindow", "保存图片"))
        self.action_save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_mean_filter.setText(_translate("MainWindow", "均值滤波\n"
""))
        self.action_gauss_fliter.setText(_translate("MainWindow", "高斯滤波\n"
""))
        self.action_median_filter.setText(_translate("MainWindow", "中值滤波\n"
"(椒盐)"))
        self.action_linear.setText(_translate("MainWindow", "线性变换\n"
""))
        self.action_power.setText(_translate("MainWindow", "幂变换\n"
""))
        self.action_6.setText(_translate("MainWindow", "一阶差分"))
        self.action_7.setText(_translate("MainWindow", "二阶差分"))
        self.action_2gray.setText(_translate("MainWindow", "转为灰度图"))
        self.action_2binary.setText(_translate("MainWindow", "转为二值图"))
        self.action_color_reverse.setText(_translate("MainWindow", "颜色反转"))
        self.action_gaussian_noise.setText(_translate("MainWindow", "高斯噪声"))
        self.action_salt_noise.setText(_translate("MainWindow", "椒盐噪声(default:0.01)"))
        self.action_own_2gray.setText(_translate("MainWindow", "转灰度图"))
        self.action_own_2binary.setText(_translate("MainWindow", "转二值图"))
        self.action_noisy_menu.setText(_translate("MainWindow", "加噪去噪控制面板\n"
""))
        self.action_gray_enhance_menu.setText(_translate("MainWindow", "灰度增强控制面板\n"
""))
        self.action_hdzft.setText(_translate("MainWindow", "灰度直方图"))

