# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\github\final_work\final_work_最终版\noisy.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(537, 321)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 30, 481, 241))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.jyzs_value = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.jyzs_value.setSingleStep(0.01)
        self.jyzs_value.setObjectName("jyzs_value")
        self.horizontalLayout.addWidget(self.jyzs_value)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.gszs_value1 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.gszs_value1.setObjectName("gszs_value1")
        self.horizontalLayout_2.addWidget(self.gszs_value1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.gszs_value2 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.gszs_value2.setObjectName("gszs_value2")
        self.horizontalLayout_2.addWidget(self.gszs_value2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 2, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.value_jzlb1 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.value_jzlb1.setObjectName("value_jzlb1")
        self.horizontalLayout_3.addWidget(self.value_jzlb1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.value_jzlb2 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.value_jzlb2.setObjectName("value_jzlb2")
        self.horizontalLayout_3.addWidget(self.value_jzlb2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 4, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 3, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 2, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        self.value_gslb_ab = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.value_gslb_ab.setObjectName("value_gslb_ab")
        self.horizontalLayout_5.addWidget(self.value_gslb_ab)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.value_gslb_c = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.value_gslb_c.setObjectName("value_gslb_c")
        self.horizontalLayout_5.addWidget(self.value_gslb_c)
        self.gridLayout.addLayout(self.horizontalLayout_5, 3, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.value_zzlb = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.value_zzlb.setObjectName("value_zzlb")
        self.horizontalLayout_4.addWidget(self.value_zzlb)
        self.horizontalLayout_4.setStretch(0, 5)
        self.horizontalLayout_4.setStretch(1, 5)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 2, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 4, 1, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout.addWidget(self.line_8, 1, 1, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout.addWidget(self.line_9, 0, 1, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout.addWidget(self.line_10, 0, 3, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout.addWidget(self.line_11, 1, 3, 1, 1)
        self.line_12 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout.addWidget(self.line_12, 3, 3, 1, 1)
        self.line_13 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout.addWidget(self.line_13, 4, 3, 1, 1)
        self.submit_zzlb = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.submit_zzlb.setObjectName("submit_zzlb")
        self.gridLayout.addWidget(self.submit_zzlb, 1, 4, 1, 1)
        self.submit_jyzs = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.submit_jyzs.setObjectName("submit_jyzs")
        self.gridLayout.addWidget(self.submit_jyzs, 0, 4, 1, 1)
        self.submit_gszs = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.submit_gszs.setObjectName("submit_gszs")
        self.gridLayout.addWidget(self.submit_gszs, 2, 4, 1, 1)
        self.submit_gslb = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.submit_gslb.setObjectName("submit_gslb")
        self.gridLayout.addWidget(self.submit_gslb, 3, 4, 1, 1)
        self.submit_jzlb = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.submit_jzlb.setObjectName("submit_jzlb")
        self.gridLayout.addWidget(self.submit_jzlb, 4, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 537, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "加噪&去噪"))
        self.label_2.setText(_translate("MainWindow", "高斯噪声"))
        self.label_3.setText(_translate("MainWindow", "算术均值滤波"))
        self.label.setText(_translate("MainWindow", "椒盐噪声"))
        self.label_5.setText(_translate("MainWindow", "百分比"))
        self.label_11.setText(_translate("MainWindow", "高斯滤波"))
        self.label_6.setText(_translate("MainWindow", "均值"))
        self.label_7.setText(_translate("MainWindow", "标准差"))
        self.label_8.setText(_translate("MainWindow", "m"))
        self.label_9.setText(_translate("MainWindow", "n(=m)"))
        self.label_12.setText(_translate("MainWindow", "模板(y*y)"))
        self.label_13.setText(_translate("MainWindow", "标准差"))
        self.label_4.setText(_translate("MainWindow", "中值滤波"))
        self.label_10.setText(_translate("MainWindow", "孔径的尺寸"))
        self.submit_zzlb.setText(_translate("MainWindow", "确认"))
        self.submit_jyzs.setText(_translate("MainWindow", "确认"))
        self.submit_gszs.setText(_translate("MainWindow", "确认"))
        self.submit_gslb.setText(_translate("MainWindow", "确认"))
        self.submit_jzlb.setText(_translate("MainWindow", "确认"))

