# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(901, 474)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.infoTextArea = QtWidgets.QTextBrowser(self.centralwidget)
        self.infoTextArea.setGeometry(QtCore.QRect(620, 10, 261, 291))
        self.infoTextArea.setDocumentTitle("")
        self.infoTextArea.setObjectName("infoTextArea")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 601, 309))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.MainLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.MainLayout.setContentsMargins(0, 0, 0, 0)
        self.MainLayout.setObjectName("MainLayout")
        self.img_MainLayout = QtWidgets.QHBoxLayout()
        self.img_MainLayout.setObjectName("img_MainLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.text_Origin = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.text_Origin.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.text_Origin.setAlignment(QtCore.Qt.AlignCenter)
        self.text_Origin.setObjectName("text_Origin")
        self.gridLayout.addWidget(self.text_Origin, 0, 0, 1, 1)
        self.text_Prev = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.text_Prev.setAlignment(QtCore.Qt.AlignCenter)
        self.text_Prev.setObjectName("text_Prev")
        self.gridLayout.addWidget(self.text_Prev, 0, 1, 1, 1)
        self.menu_MainLayout = QtWidgets.QGridLayout()
        self.menu_MainLayout.setObjectName("menu_MainLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_open = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.button_open.setObjectName("button_open")
        self.horizontalLayout.addWidget(self.button_open)
        self.button_save = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.button_save.setObjectName("button_save")
        self.horizontalLayout.addWidget(self.button_save)
        self.menu_MainLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.menu_MainLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_1 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.button_1.setObjectName("button_1")
        self.verticalLayout.addWidget(self.button_1)
        self.button_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.button_2.setObjectName("button_2")
        self.verticalLayout.addWidget(self.button_2)
        self.button_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.button_3.setObjectName("button_3")
        self.verticalLayout.addWidget(self.button_3)
        self.button_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.button_4.setObjectName("button_4")
        self.verticalLayout.addWidget(self.button_4)
        self.button_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.button_5.setObjectName("button_5")
        self.verticalLayout.addWidget(self.button_5)
        self.button_6 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.button_6.setObjectName("button_6")
        self.verticalLayout.addWidget(self.button_6)
        self.button_7 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.button_7.setObjectName("button_7")
        self.verticalLayout.addWidget(self.button_7)
        self.button_8 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.button_8.setObjectName("button_8")
        self.verticalLayout.addWidget(self.button_8)
        self.menu_MainLayout.addLayout(self.verticalLayout, 2, 1, 1, 1)
        self.menu_MainLayout.setRowStretch(0, 2)
        self.gridLayout.addLayout(self.menu_MainLayout, 1, 2, 1, 1)
        self.img_origin = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.img_origin.setAlignment(QtCore.Qt.AlignCenter)
        self.img_origin.setObjectName("img_origin")
        self.gridLayout.addWidget(self.img_origin, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.img_MainLayout.addLayout(self.gridLayout)
        self.MainLayout.addLayout(self.img_MainLayout)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 340, 601, 61))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 901, 23))
        self.menubar.setObjectName("menubar")
        self.menuwenjian = QtWidgets.QMenu(self.menubar)
        self.menuwenjian.setObjectName("menuwenjian")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuwenjian.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "图像处理-wjsaya.top"))
        self.infoTextArea.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">显示名    |    objectName</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">原图    |    img_origin</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">预览    |    img_prev</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">打开    |    button_open</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">保存    |    button_save</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">从上到下    |    1,2,3,4,5...</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.text_Origin.setText(_translate("MainWindow", "原图"))
        self.text_Prev.setText(_translate("MainWindow", "预览"))
        self.button_open.setText(_translate("MainWindow", "打开"))
        self.button_save.setText(_translate("MainWindow", "保存"))
        self.button_1.setText(_translate("MainWindow", "彩色->灰度"))
        self.button_2.setText(_translate("MainWindow", "灰度->二值"))
        self.button_3.setText(_translate("MainWindow", "几何变换"))
        self.button_4.setText(_translate("MainWindow", "去噪"))
        self.button_5.setText(_translate("MainWindow", "PushButton"))
        self.button_6.setText(_translate("MainWindow", "边缘提取(一阶差分)"))
        self.button_7.setText(_translate("MainWindow", "加噪"))
        self.button_8.setText(_translate("MainWindow", "退出"))
        self.img_origin.setText(_translate("MainWindow", "原图"))
        self.label_3.setText(_translate("MainWindow", "预览"))
        self.label.setText(_translate("MainWindow", "标记"))
        self.menuwenjian.setTitle(_translate("MainWindow", "文件"))
        self.menu.setTitle(_translate("MainWindow", "关于"))
        self.menu_2.setTitle(_translate("MainWindow", "编辑"))

