# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1178, 1040)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.infoTextArea = QtWidgets.QTextBrowser(self.centralwidget)
        self.infoTextArea.setGeometry(QtCore.QRect(510, 540, 256, 192))
        self.infoTextArea.setObjectName("infoTextArea")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(120, 30, 981, 481))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.MainLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.MainLayout.setContentsMargins(0, 0, 0, 0)
        self.MainLayout.setObjectName("MainLayout")
        self.img_MainLayout = QtWidgets.QHBoxLayout()
        self.img_MainLayout.setObjectName("img_MainLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.text_Prev = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.text_Prev.setAlignment(QtCore.Qt.AlignCenter)
        self.text_Prev.setObjectName("text_Prev")
        self.gridLayout.addWidget(self.text_Prev, 0, 1, 1, 1)
        self.img_Origin = QtWidgets.QGraphicsView(self.horizontalLayoutWidget_2)
        self.img_Origin.setObjectName("img_Origin")
        self.gridLayout.addWidget(self.img_Origin, 1, 0, 1, 1)
        self.text_Origin = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.text_Origin.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.text_Origin.setAlignment(QtCore.Qt.AlignCenter)
        self.text_Origin.setObjectName("text_Origin")
        self.gridLayout.addWidget(self.text_Origin, 0, 0, 1, 1)
        self.menu_MainLayout = QtWidgets.QGridLayout()
        self.menu_MainLayout.setObjectName("menu_MainLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_open = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.button_open.setObjectName("button_open")
        self.horizontalLayout.addWidget(self.button_open)
        self.button_save = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.button_save.setObjectName("button_save")
        self.horizontalLayout.addWidget(self.button_save)
        self.menu_MainLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.menu_MainLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_9 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout.addWidget(self.pushButton_10)
        self.pushButton_7 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout.addWidget(self.pushButton_7)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_6 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout.addWidget(self.pushButton_6)
        self.pushButton_8 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout.addWidget(self.pushButton_8)
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.menu_MainLayout.addLayout(self.verticalLayout, 2, 1, 1, 1)
        self.menu_MainLayout.setRowStretch(0, 2)
        self.gridLayout.addLayout(self.menu_MainLayout, 1, 2, 1, 1)
        self.img_Prev = QtWidgets.QGraphicsView(self.horizontalLayoutWidget_2)
        self.img_Prev.setObjectName("img_Prev")
        self.gridLayout.addWidget(self.img_Prev, 1, 1, 1, 1)
        self.img_MainLayout.addLayout(self.gridLayout)
        self.MainLayout.addLayout(self.img_MainLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1178, 23))
        self.menubar.setObjectName("menubar")
        self.menuwenjian = QtWidgets.QMenu(self.menubar)
        self.menuwenjian.setObjectName("menuwenjian")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuwenjian.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.infoTextArea.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">显示名    |    objectName</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">原图    |    img_origin</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">预览    |    img_prev</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.text_Prev.setText(_translate("MainWindow", "预览"))
        self.text_Origin.setText(_translate("MainWindow", "原图"))
        self.button_open.setText(_translate("MainWindow", "打开"))
        self.button_save.setText(_translate("MainWindow", "保存"))
        self.pushButton_4.setText(_translate("MainWindow", "彩色->灰度"))
        self.pushButton_9.setText(_translate("MainWindow", "灰度->二值"))
        self.pushButton_10.setText(_translate("MainWindow", "几何变换"))
        self.pushButton_7.setText(_translate("MainWindow", "去噪"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_6.setText(_translate("MainWindow", "边缘提取(一阶差分)"))
        self.pushButton_8.setText(_translate("MainWindow", "加噪"))
        self.pushButton_5.setText(_translate("MainWindow", "退出"))
        self.menuwenjian.setTitle(_translate("MainWindow", "文件"))
        self.menu.setTitle(_translate("MainWindow", "关于"))
        self.menu_2.setTitle(_translate("MainWindow", "编辑"))

